- hosts: localhost
  connection: local
  vars_prompt:
    - name: db_username
      prompt: "Database Username"
      private: no
    - name: db_password
      prompt: "Database Password"
      private: yes

  tasks:
  - name: POSTGRESQL PLAYS 
    include: postgresql.yaml

  - name: REDIS PLAYS
    include: redis.yaml

  - name: SYSTEM PACKAGES PLAYS
    include: system-packages.yaml 

  - name: CLONE NAUTOBOT PLAYS
    include: git.yaml

  - name: SYSTEM ACCOUNT PLAYS
    include: account.yaml

  - name: NAUTOBOT INSTALL PLAYS
    include: nautobot-install.yaml

  - name: GUNICORN PLAYS
    include: gunicorn.yaml

  - name: SYSTEMD PLAYS
    include: systemd.yaml

  - name: SSL CERTIFICATE PLAYS
    include: openssl.yaml

  - name: NGINX PLAYS
    include: nginx.yaml

  - name: SELINUX PLAYS
    include: selinux.yaml

  handlers:
  - include: handlers.yaml
