- name: INSTALL SYSTEM PACKAGES
  ansible.builtin.yum:
    name:
    - git
    - python38
    - python38-devel
    - python3-pip
    state: present

# - name: INSTALL NAUTOBOT FROM PIP
#   ansible.builtin.pip:
#     name: nautobot
#     state: present
